# Generated by Django 5.2.8 on 2025-11-28 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('CHILE', 'Chile'), ('PERU', 'Perú'), ('COLOMBIA', 'Colombia')], max_length=20, verbose_name='País')),
                ('tipo', models.CharField(choices=[('IVA', 'IVA / IGV'), ('RENTA', 'Impuesto a la Renta'), ('ADUANA', 'Impuesto Aduanero')], max_length=20, verbose_name='Tipo de Impuesto')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factor', models.DecimalField(decimal_places=4, help_text='Ej: 0.19 para 19%', max_digits=5)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
